### ISSUE TITLE
Working examples

### ISSUE THREAD

**Issue by renestalder** [UseAllFive/scrub.js#2]
At the moment this is the only one project I found which covers the case of changing a video's timeline by scrolling.

Unfortunately the examples are not working anymore or are no longer online. Would you recommend an alternative solution or is this still a good working one?

**Comment by casconed** [comment]
Both examples linked from the README work for me. What browser are you using? Do you get any console errors?

**Comment by renestalder** [comment]
Looks like this for me in latest Google Chrome (Video mapped to div example)
![screenshot 2015-03-26 11 14 03](https://cloud.githubusercontent.com/assets/105358/6844095/4d9b0f54-d3a9-11e4-9416-34cbf1d35cef.png)

Console shows this

![screenshot 2015-03-26 11 14 08](https://cloud.githubusercontent.com/assets/105358/6844098/59c20ce2-d3a9-11e4-95e5-457b29efc358.png)

**Comment by renestalder** [comment]
I tested with several other browsers and ignognito mode in chrome now. I have a browser plugin which blocks contents from third-party- sources, if the site with https tries to load sources from http.

If I allow loading the sources, it works. 
Your '.mov' file and one jQuery file (seems it's embedded twice) try to load from a non-https source which causes the problem.

**Comment by casconed** [comment]
Got it, thanks for running that down!
